title: Keep it simple, stupid
user: Xiao-Ou Zhang
author:
  name: Xiao-Ou Zhang, PhD
  description: I'm a <a href='xiaoou_zhang_cv.pdf'>computational biologist</a> who
    is passionate about <a href='https://scholar.google.com/citations?user=KpX6MewAAAAJ'>RNA</a> and
    <a href='projects.html'>data mining</a>!
gems: [github-pages]
